services:
  postgres:
    image: postgres:16-alpine
    container_name: nexo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nexo
      POSTGRES_PASSWORD: nexo1234
      POSTGRES_DB: nexo_turnos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
